name: Build Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "21"

      - name: Flutter pub Get
        run: flutter pub get

      - name: Build Android using Flutter
        run: flutter build aab